apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.app.service.type "NodePort") .Values.app.service.nodePort }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
