export const ingressText = {
  annotations: "注解",
  noAnnotations: "无注解",
  annotationDialogTitle: "Ingress 注解",
  annotationDialogDescription: "按键名排序展示；长内容会自动换行，不影响页面宽度。",
  annotationLoading: "正在读取注解…",
  annotationLoadFailed: "注解读取失败",
  close: "关闭",
  mobileHosts: "Hosts",
  mobileBackends: "后端 Service",
  mobileClass: "IngressClass",
  mobileOrigin: "回源",
  mobileAge: "创建时间",
  managed: "已托管",
  unmanaged: "未托管",
  edit: "编辑",
  remove: "删除",
  publishSummary: "填写 Service 与域名即可生成 Ingress，可选同步到宝塔并启用 HTTPS。",
  configurationDetails: "查看注解与回源规则",
} as const;
